// Generated by Haxe 3.4.7
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	var graphic = new PIXI.Graphics();
	graphic.beginFill(16711680,0.4);
	graphic.drawRect(200,150,400,300);
	graphic.endFill();
};
var pixi_core_renderers_webgl_filters_CurrentState = function() { };
Main.main();
})();
